import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePaths = ["js/model.js", "js/storage.js", "js/app.js"];

function prepareSource(source) {
  return source
    .replace(/^import\s+\{[\s\S]*?\}\s+from\s+["'][^"']+["'];\s*/gm, "")
    .replace(/^export\s+/gm, "")
    .trim();
}

const sources = await Promise.all(
  sourcePaths.map(async (relativePath) => {
    const source = await readFile(resolve(projectRoot, relativePath), "utf8");
    return prepareSource(source);
  }),
);

const bundle = `// Generated by npm run build from the modular source files in js/.
// This classic script works from file:// URLs and static web hosts.
(() => {
  "use strict";

${sources.join("\n\n")}
})();
`;

await writeFile(resolve(projectRoot, "js/app.bundle.js"), bundle, "utf8");
